# Generated by Django 4.0.1 on 2022-01-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='EmailID',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='account',
            name='Name',
        ),
        migrations.AlterField(
            model_name='account',
            name='Publicity',
            field=models.CharField(blank=True, choices=[('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Whatsapp', 'Whatsapp'), ('LinkedIn', 'LinkedIn'), ('College', 'College'), ('Others', 'Others')], max_length=50, null=True),
        ),
    ]
